### ISSUE TITLE
Feature Request - Support for conditional groups based on conditions evaluating to true

### ISSUE THREAD

**Issue by DII-dsward** [oracle/oci-ansible-collection#122]
Need the ability to create groups based on Jinja2 expressions evaluating to true. Here is an example with a few use cases.
```
---
conditional_groups:
  #group all the hosts into a group
  all_the_hosts: true
  #group hosts when a string in hostname is found
  production_hosts: "'prod' in hostname"
  #group hosts based on regex string found in id
  db_hosts: "'dbnode' in id"
  #group host based on freeform tags
  app1: "'app1' in freeform_tags.application"
```
For example there is a azure_rm dynamic inventory plugin that does this
https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_inventory.html#ansible-collections-azure-azcollection-azure-rm-inventory

**Comment by dineshsuthar786** [comment]
Thanks for this feature request, we will check this and update you.

**Comment by dineshsuthar786** [comment]
@DII-dsward, Please check `groups` option in oci inventory plugin, which create groups based on jinja2 expresion. Refer the docs [here](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/ansibleinventoryintro.htm#Using_Dynamic_Groups). Let us know if you need anything else.

**Comment by DII-dsward** [comment]
Ok, i did not see this in the rst or the inventory oci.py script. I will add this to our inventory script as follows:

```yaml
---
# https://github.com/oracle/oci-ansible-collection/blob/master/docs/collections/oracle/oci/oci_inventory.rst
plugin: oracle.oci.oci
fetch_db_hosts: False
fetch_compute_hosts: True
enable_parallel_processing: yes
primary_vnic_only: true
regions:
  - us-ashburn-1
  - us-phoenix-1
hostname_format_preferences:
  - "display_name+'.domain.com"
groups:
  production: "hostname[:1] == 'P'"

```
