### ISSUE TITLE
How To\Documentation Request - Write cost tracking tags to oci resources.

### ISSUE THREAD

**Issue by DII-dsward** [oracle/oci-ansible-collection#127]
I am using the following playbook to tag freeform_tags. I see in the oci_compute_instance.py that defined_tags is available. I need to switch this to defined_tags to have cost tracking tags. Can you help demonstrate what this needs to look like?

```yaml
    - name: Update Compute Instance Tags
      delegate_to: localhost
      oci_compute_instance:
        instance_id: "{{ id }}"
        region: "{{ Region }}"
        freeform_tags: "{'Application_Stack': '{{ Application_Stack }}'}"
```

I believe it will look something like this in the end?
```yaml
- name: Create defined tag namespace
  oci_identity_tag_namespace:
    compartment_id: "'{{ rootcomp_ocid }}"
    name: "{{ Application_Stack }}"
    description: "{{ Application_Stack }} Resources"
  register: costtracking_tag

- name: Create defined tag
  oci_identity_tag:
    tag_namespace_id: "{{ costtracking_tag.id }}"
    name: Application_Stack

- name: Update Compute Instance Tags
  delegate_to: localhost
  oci_compute_instance:
    instance_id: "{{ id }}"
    region: "{{ Region }}"
    defined_tags: "{'Application_Stack': '{{ Application_Stack }}'}"
```

I'm looking at these docs:
- https://github.com/oracle/oci-ansible-collection/blob/master/plugins/modules/oci_compute_instance.py
- https://github.com/oracle/oci-ansible-collection/blob/master/plugins/modules/oci_identity_tag.py
- https://github.com/oracle/oci-ansible-collection/blob/master/plugins/modules/oci_identity_tag.py
- https://github.com/oracle/oci-ansible-collection/blob/master/docs/collections/oracle/oci/oci_compute_instance_module.rst
- https://docs.oracle.com/en-us/iaas/Content/Tagging/Tasks/usingcosttrackingtags.htm
