### ISSUE TITLE
oci_compute_instance not fully idempotent

### ISSUE THREAD

**Issue by DII-jkalbright** [oracle/oci-ansible-collection#133]
When using `oci_compute_instance` for a compute instance that already exists, it fails with:

`failed with errors: [{\n  \"code\": \"vcn-error\",\n  \"message\": \"A problem occurred while preparing the instance's VNIC.  (Hostname xxxxx is already used in subnet ocid1.subnet.oc1.phx.xxxxxx)\"`

**Expected behavior**

In order for oci_compute_instance to be truly idempotent, I would expect this to gracefully continue.

Environment
Tower 3.8.4

OS version:
RHEL 8

Ansible version:

ansible --version
ansible 2.9.19
config file = /etc/ansible/ansible.cfg
configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.6/site-packages/ansible
executable location = /usr/bin/ansible
python version = 3.6.8 (default, Sep 9 2021, 07:49:02) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]

OCI Python SDK version:
python3 -c "import oci;print(oci.version)"
2.46.0

OCI Ansible Modules version:
---
collections:
  - name: oracle.oci
    version: 2.36.0
ansible-galaxy collection list

# ansible-galaxy collection list
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')

**Ansible playbook to reproduce the issue**

    - name: Launch a Compute Instance
      oci_compute_instance:
        name:  "{{ VM_HOSTNAME }}"
        region: "{{ OCI_REGION }}"
        availability_domain: "{{ VM_INSTANCE_AD }}"
        compartment_id: "{{ VM_COMPARTMENT_OCID }}"
        shape: "{{ VM_SHAPE }}"
        shape_config:
          ocpus: "{{ ocpus | int }}"
        source_details:
          source_type: image
          image_id: "{{ latest_image_ocid }}"
        metadata:
          ssh_authorized_keys: "{{ ssh_keys | join('\n') }}"
        create_vnic_details:
          assign_public_ip: False
          hostname_label: "{{ VM_HOSTNAME }}"
          subnet_id: "{{ VM_SUBNET_OCID }}"
        freeform_tags: "{'AnsibleState': 'Provisioning'}"
      register: vmdetails 
    - set_fact:
        vm_instance_ip: "{{ vmdetails.instance.primary_private_ip }}"
        instance_id: "{{ vmdetails.instance.id }}"

**Comment by sagar2938** [comment]
@DII-jkalbright , thanks for providing all the details. Could you also provide the debug logs of the playbook task? 
you can enable the debug logs by following this https://github.com/oracle/oci-ansible-collection/blob/master/FAQ.md#how-to-enable-debug-mode

**Comment by DII-jkalbright** [comment]
{
    "msg": "Work request ocid1.coreservicesworkrequest.oc1.phx.xxxfailed with errors: [{\n  \"code\": \"vcn-error\",\n  \"message\": \"A problem occurred while preparing the instance's VNIC.  (Hostname dvmnaodiapp02 is already used in subnet ocid1.subnet.oc1.phx.xxx)\",\n  \"timestamp\": \"2021-12-09T17:45:28.363000+00:00\"\n}]",
    "invocation": {
        "module_args": {
            "name": "XXX",
            "region": "us-phoenix-1",
            "availability_domain": "IAYY:PHX-AD-3",
            "compartment_id": "ocid1.compartment.oc1..xxx",
            "shape": "VM.Standard2.1",
            "shape_config": {
                "ocpus": 1,
                "memory_in_gbs": null,
                "baseline_ocpu_utilization": null
            },
            "source_details": {
                "source_type": "image",
                "image_id": "ocid1.image.oc1.phx.xxx",
                "boot_volume_size_in_gbs": null,
                "kms_key_id": null,
                "boot_volume_id": null
            },
            "metadata": {
                "ssh_authorized_keys": "xxx"
            },
            "create_vnic_details": {
                "assign_public_ip": false,
                "hostname_label": "XXX",
                "subnet_id": "ocid1.subnet.oc1.phx.xxx",
                "assign_private_dns_record": null,
                "defined_tags": null,
                "display_name": null,
                "freeform_tags": null,
                "nsg_ids": null,
                "private_ip": null,
                "skip_source_dest_check": null,
                "vlan_id": null
            },
            "freeform_tags": {
                "AnsibleState": "Provisioning"
            },
            "display_name": "XXX",
            "auth_type": "api_key",
            "force_create": false,
            "wait": true,
            "state": "present",
            "config_file_location": null,
            "config_profile_name": null,
            "api_user": null,
            "api_user_fingerprint": null,
            "api_user_key_file": null,
            "api_user_key_pass_phrase": null,
            "tenancy": null,
            "key_by": null,
            "wait_timeout": null,
            "capacity_reservation_id": null,
            "dedicated_vm_host_id": null,
            "defined_tags": null,
            "extended_metadata": null,
            "fault_domain": null,
            "hostname_label": null,
            "image_id": null,
            "ipxe_script": null,
            "launch_options": null,
            "instance_options": null,
            "availability_config": null,
            "preemptible_instance_config": null,
            "agent_config": null,
            "subnet_id": null,
            "is_pv_encryption_in_transit_enabled": null,
            "platform_config": null,
            "instance_id": null,
            "preserve_boot_volume": null
        }
    },
    "_ansible_no_log": false,
    "changed": false
}

**Comment by DII-jkalbright** [comment]
Getting this debug log for you is a bit delayed because the steps needed to generate it require changes to our tower server which I do not have access to.  However, I am unsure why the log is needed.  I am sure it would help, but I also feel like this issue is very easily reproduceable thus me getting this log is a bit unnecessary.

**Comment by sagar2938** [comment]
@DII-jkalbright , the oci_compute_instance is idempotent. The debug logs will tell us which property of compute instance is causing the idempotence issue. Can you share the oci_compute_instance_facts module result for the above data?

**Comment by DII-jkalbright** [comment]
Okay.  Perhaps **idempotent** was the wrong word here.  Let me be a little bit more descriptive.

If I have an existing compute instance in OCI named "MYINSTANCE01", and then I run the module `oci_compute_instance` with `state: present` and `name: MYINSTANCE01` (the same name as the example existing instance), the module will fail with the error `failed with errors: [{\n \"code\": \"vcn-error\",\n \"message\": \"A problem occurred while preparing the instance's VNIC. (Hostname MYINSTANCE01 is already used in subnet ocid1.subnet.oc1.phx.xxxexamplexxx)\"`.

I expect this scenario to gracefully continue to the next task in my ansible playbook, but it does not.  The fact that the error states that it is "preparing the instance's VNIC" tells me that it is _**trying to do something that it should not be doing**_.  

The issue here is this forces me to write additional ansible to check whether the instance already exists.  I should not have to do that.  Then the verbiage saying "preparing the instance's VNIC" is indicating that it is in fact not idempotent.

Either way, whether Oracle believes that the module is "idempotent" does not matter because that is not the core issue here.  The core issue is the behavior and not what it is being called.

**Comment by DII-jkalbright** [comment]
Here is the output from `oci_compute_instance_facts` that I just ran in a playbook right before the playbook ran `oci_compute_instance` and failed with the issue.

```yaml
{
    "existing_compute_instance": {
        "instances": [
            {
                "availability_domain": "IAYy:PHX-AD-3",
                "capacity_reservation_id": null,
                "compartment_id": "ocid1.compartment.oc1..aaaaaaaaoblvupekjxxxexample",
                "dedicated_vm_host_id": null,
                "defined_tags": {
                    "CostTracking": {
                        "Application_Stack": ""
                    }
                },
                "display_name": "MYINSTANCE01",
                "extended_metadata": {},
                "fault_domain": "FAULT-DOMAIN-2",
                "freeform_tags": {
                    "Secondary_DC": "",
                    "Primary_DC": "",
                    "Business_Unit": "",
                    "AnsibleState": "Managed",
                    "Business_Contact": "",
                    "Business_Owner": ""
                },
                "id": "ocid1.instance.oc1.phx.anyhqljtfk7xxxexample",
                "image_id": "ocid1.image.oc1.phx.aaaaaaaaqpk3kgliqneaxxxexample",
                "ipxe_script": null,
                "launch_mode": "PARAVIRTUALIZED",
                "launch_options": {
                    "boot_volume_type": "PARAVIRTUALIZED",
                    "firmware": "UEFI_64",
                    "network_type": "PARAVIRTUALIZED",
                    "remote_data_volume_type": "PARAVIRTUALIZED",
                    "is_pv_encryption_in_transit_enabled": false,
                    "is_consistent_volume_naming_enabled": true
                },
                "instance_options": {
                    "are_legacy_imds_endpoints_disabled": false
                },
                "availability_config": {
                    "is_live_migration_preferred": null,
                    "recovery_action": "RESTORE_INSTANCE"
                },
                "preemptible_instance_config": null,
                "lifecycle_state": "RUNNING",
                "metadata": {
                    "ssh_authorized_keys": "xxxexamplexxx"
                },
                "region": "phx",
                "shape": "VM.Standard2.1",
                "shape_config": {
                    "ocpus": 1,
                    "memory_in_gbs": 15,
                    "baseline_ocpu_utilization": null,
                    "processor_description": "2.0 GHz Intel® Xeon® Platinum 8167M (Skylake)",
                    "networking_bandwidth_in_gbps": 1,
                    "max_vnic_attachments": 2,
                    "gpus": 0,
                    "gpu_description": null,
                    "local_disks": 0,
                    "local_disks_total_size_in_gbs": null,
                    "local_disk_description": null
                },
                "source_details": {
                    "source_type": "image",
                    "boot_volume_size_in_gbs": null,
                    "image_id": "ocid1.image.oc1.phx.aaaaaaaaqpk3kgliqxxxexample",
                    "kms_key_id": null
                },
                "system_tags": {},
                "time_created": "2021-12-18T18:48:31.281000+00:00",
                "agent_config": {
                    "is_monitoring_disabled": false,
                    "is_management_disabled": false,
                    "are_all_plugins_disabled": false,
                    "plugins_config": null
                },
                "time_maintenance_reboot_due": null,
                "platform_config": null,
                "primary_public_ip": null,
                "primary_private_ip": "1.2.3.4"
            }
        ],
        "failed": false,
        "changed": false
    },
    "_ansible_verbose_always": true,
    "_ansible_no_log": false,
    "changed": false
}
```
