### ISSUE TITLE
Issue getting DB Node IPs with new Exadata Elastic Shape

### ISSUE THREAD

**Issue by joshmullis** [oracle/oci-ansible-collection#134]
## Issue Report

**Describe the issue**

We are seeing some strange behavior trying to get the IPs of Cloud Exadata VM Cluster “Elastic” DB nodes.
 
For “Exadata Base” shapes, this gets the correct VNIC/IP (as we see in the oci web console), however with the new “Elastic” shape, we instead get these VNICs for each node…
 
1)	One with “-client1” appended to the end of the node name (this is not the node IP in oci web that we expect):
 
"hostname-label": "testexadata-g5c8p1-client1"
"private-ip": "10.10.45.168" 
 
 
2)	…and one with the correct node name we expect, but a “null” ip
 
"hostname": "testexadata-g5c8p1"
"primary_private_ip": null
 
 
I’m guessing the new elastic Exadata nodes are doing something different with their VNICs that we need to account for.
 
Is this the correct method to get the Cloud Exadata DB Node IPs regardless of shape?
Or is there another ansible module we should be using?
 

**Expected behavior**

We would expect this to return the DB Node IP as we see it in the OCI web console

**Environment**

* OS version:  OEL 7.6

* Ansible version:

```
ansible 2.9.7
  config file = /home/testuser/ansible.cfg
  configured module search path = [u'/home/testuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Dec  4 2019, 17:34:13) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.1)]
```

* OCI Python SDK version:

```
2.36.0
```

* OCI Ansible Modules version:

```
2.36.0
```

**Ansible playbook to reproduce the issue**

```
    - name: Get DB Node Facts
      oracle.oci.oci_database_db_node_facts:
        compartment_id: "ocid1.compartment.oc1..<redacted>"
        vm_cluster_id: "ocid1.cloudvmcluster.oc1.<redacted>"
      register: db_node_facts
 
    - name: Look up DB node vnic details
      oracle.oci.oci_network_vnic_facts:
        vnic_id: "{{ item.vnic_id }}"
      register: db_node_vnic_facts
      loop: "{{ db_node_facts.db_nodes }}"
```
