### ISSUE TITLE
oci_loadbalancer_load_balancer_facts not returning load balancer data

### ISSUE THREAD

**Issue by DII-jkalbright** [oracle/oci-ansible-collection#137]
The oci_loadbalancer_load_balancer_facts module is not returning load balancer data.

This compartment in this snippet contains two load balancers yet none are returned.
```
            {
                "load_balancers": [],
                "invocation": {
                    "module_args": {
                        "region": "us-ashburn-1",
                        "compartment_id": "ocid1.tenancy.oc1..xxx",
                        "auth_type": "api_key",
                        "config_file_location": null,
                        "config_profile_name": null,
                        "api_user": null,
                        "api_user_fingerprint": null,
                        "api_user_key_file": null,
                        "api_user_key_pass_phrase": null,
                        "tenancy": null,
                        "load_balancer_id": null,
                        "detail": null,
                        "sort_by": null,
                        "sort_order": null,
                        "display_name": null,
                        "lifecycle_state": null
                    }
                },
                "failed": false,
                "changed": false,
                "item": [
                    "us-ashburn-1",
                    {
                        "id": "ocid1.compartment.oc1..aaaaaaaajvwjevkviiy4jyn5rc7t3hhrwi7pwbd6voiekfnfwvg64i6xlmua",
                        "compartment_id": "ocid1.tenancy.oc1..xxx",
                        "name": "XXX",
                        "description": "Non Production XXX Resources in Phoenix",
                        "time_created": "2020-11-06T16:52:50.870000+00:00",
                        "lifecycle_state": "ACTIVE",
                        "inactive_status": null,
                        "is_accessible": null,
                        ....
                    }
                ],
                "ansible_loop_var": "item"
            },
```

**Expected behavior**

It is expected that the load_balancers key in the return data would contain data for the load balancers present in the compartment of the specified region.

**Environment**
Tower 3.8.4

**OS version:**
RHEL 8

**Ansible version:**
ansible --version
ansible 2.9.19
config file = /etc/ansible/ansible.cfg
configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.6/site-packages/ansible
executable location = /usr/bin/ansible
python version = 3.6.8 (default, Sep 9 2021, 07:49:02) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]

**OCI Python SDK version:**
python3 -c "import oci;print(oci.version)"
2.46.0

**OCI Ansible Modules version:**
collections:

name: oracle.oci
version: 2.36.0
ansible-galaxy collection list
ansible-galaxy collection list
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')

**Ansible playbook to reproduce the issue**
```
  vars:
      OCI_REGIONS:
        - "us-ashburn-1"
        - "us-phoenix-1"
      OCI_TENANCY: "ocid1.tenancy.oc1..XXX"

  tasks: 
    - name: Get list of compartments
      oci_identity_compartment_facts: 
        lifecycle_state: "ACTIVE"
        parent_compartment_id: "{{ OCI_TENANCY }}"
        compartment_id_in_subtree: yes
      register: OCI_COMPARTMENTS

    - name: Get load balancer data
      oci_loadbalancer_load_balancer_facts:
        region: "{{ item[0] }}"
        compartment_id: "{{ item[1].compartment_id }}"
      with_nested: 
        - '{{ OCI_REGIONS }}'
        - '{{ OCI_COMPARTMENTS.compartments }}'
      register: OCI_LOAD_BALANCERS
```
