### ISSUE TITLE
[Feature Request] Make 'region' parameter not a requirement if passing resource id parameter

### ISSUE THREAD

**Issue by DII-jkalbright** [oracle/oci-ansible-collection#139]
When passing a resource's id as a module parameter then the 'region' parameter should not be a requirement.  It makes it more difficult to write succinct ansible with the OCI collection.  There is enough information in the 'id' parameter to accurately determine the region.

**Comment by sagar2938** [comment]
@DII-jkalbright , thanks for the requirement. checking it

**Comment by sagar2938** [comment]
@DII-jkalbright , whats are your pain points in configuring the region? it will help us understand the issue better

**Comment by DII-jkalbright** [comment]
Here is an example where regions, in general, are a pain point.  Not being able to target a resource without specifying region, whether it is in the web interface for OCI, or through ansible, is pretty annoying.  This should be able to be written without all of the region logic.  

If I am querying for load balancer resources, why not just give me all of them and have their respective region be a returned attribute?  And if I am querying a load balancer that has `.iad.` in the 'id' do I need to specify 'us-ashburn-1'?  It is a unique identifier, and OCI should be smart enough to find resources without telling it where to look.

```
---
  collections:
    - oracle.oci
  hosts: localhost
  connection: local

  vars:
    OCI_REGIONS:
      - "us-ashburn-1"
      - "us-phoenix-1"
  

  tasks: 

    - name: Get list of load balancers
      oci_resource_search_resource_facts:
        type: Structured
        query: "query loadbalancer resources where lifeCycleState = 'ACTIVE'"
        region: "{{ item }}"
      loop: "{{ OCI_REGIONS }}"  
      register: OCI_LOAD_BALANCERS

      set_fact:
        load_balancers: "{{ load_balancers | default([]) }} + {{ item.resources }}"
      loop: "{{ OCI_LOAD_BALANCERS.results }}"

    - name: Get load balancer data
      oci_loadbalancer_load_balancer_facts:
        region: "{{ 'us-ashburn-1' if item.identifier|regex_search('iad') else 'us-phoenix-1' }}"
        id: "{{ item.identifier }}"
        detail: 'full'
      loop: "{{ load_balancers }}"
      register: OCI_LOAD_BALANCER_DATA
```
