### ISSUE TITLE
Ansible Collection Modules appear to not support Async

### ISSUE THREAD

**Issue by AndreasFrangopoulos** [oracle/oci-ansible-collection#14]
To put my question into context, I am automating block volume attachment and preparation (formatting and mounting) for hosts (which include both Linux and Windows hosts) using Ansible in a "push configuration" i.e. a control node is pushing the configuration to each node rather than running the playbook locally. Local hosts do not have the OCI CLI or Ansible installed and therefore cannot query OCI for their particular resources. I have to therefore run a set of tasks locally on the "push" server to gather all the information I require for all resources before starting the configuration so the I pass this data as facts to the hosts.

I therefore have to get a list of all block volumes across a particular region which I have to do in a few steps since you cannot just get them for a region as a whole.
1. Get all the container OCIDS
2. Loop through each and use the oci_compute_volume_attachment_facts, and oci_identity_compartment_facts modules. to get the block volumes and block volume attachments.

The problem is that it appears you cannot loop these tasks asynchronously which means it takes around 15 seconds per compartment ocid. Not a lot but this will start to slow things down heavily when you start trying to get many resources from many different compartments.

My sample code is:
 ```
hosts: localhost
  collections:
    - oracle.oci
  tasks:
  # Get  a list of all the compartments in the tenancy
    - name: List compartments
      oci_identity_compartment_facts:
        parent_compartment_id: ocid1.tenancy.oc1..aaaaaaaagezfwxx2ucr7oXXXXXXXXXXXXXXmesohun2ouc437lfwa
        compartment_id_in_subtree: true
        access_level: "ANY"
      register: compartment_list

# Filter out deleted tenants [See Ansible Filters and json_query for info on filtering.]
    - set_fact: compartment_ids="{{ compartment_list | json_query(comp_query) }}"
      vars:
        comp_query: "compartments[? lifecycle_state=='ACTIVE'].id" 
   
   # Loop through  each compartment gathered in the previous list and get all the block volumes
   # associated with it.  Put this in a variable called region_bvas_raw 
    - name: List block volume attachment facts for region
      oci_compute_volume_attachment_facts:
        compartment_id: "{{ item }}"
      loop: "{{ compartment_ids }}"
      register: region_bvas_raw

# Turn the results into a list of maps as opposed to a list of lists 
    - set_fact: region_bvas="{{ region_bvas_raw.results | sum(attribute='volume_attachments', start=[]) }}"
      vars:
        bva_trim_query: "results[*].volume_attachments" 
    
# List all the block volumes in the region
    - name: List block volumes in region
      oci_blockstorage_volume_facts:
        compartment_id: "{{ item }}"
      loop: "{{ compartment_ids }}"
      register: region_block_volumes_raw

 # Turn the results into a list of maps as opposed to a list of lists    
    - set_fact: region_block_volumes="{{ region_block_volumes_raw.results | sum(attribute='volumes', start=[]) }}"
      vars:
        bva_trim_query: "results[*].volumes" 
```

I attempted to run the following
```
# List all the block volumes in the region
    - name: List block volumes in region
      oci_blockstorage_volume_facts:
        compartment_id: "{{ item }}"
      loop: "{{ compartment_ids }}"
      register: region_block_volumes_raw
  
```

as

```
# List all the block volumes in the region
    - name: List block volumes in region
      oci_blockstorage_volume_facts:
        compartment_id: "{{ item }}"
      loop: "{{ compartment_ids }}"
      async: 45
      poll: 0
      register: region_block_volumes_raw
```

But it doesn't return any output and still runs synchronously.

Is there a way to run these async?
