### ISSUE TITLE
Removing an existing path_route_set from listener

### ISSUE THREAD

**Issue by cgmejica** [oracle/oci-ansible-collection#159]
We are migrating our existing loadbalancers to use Routing Policy instead of Path Route Sets.  However I am unable to remove the existing path route set from the listener.

Is there a way to set the existing path_route_set to "NULL" ?

Example :
```
  - name: remove path route policy
    oci_loadbalancer_listener:
       load_balancer_id: <loadbalancer_id>
       name: <listener_name>
       path_route_set_name: "None" or "NULL"
```
