### ISSUE TITLE
using oci_identity_dynamic_group module results in an empty field for matching rule in the UI.

### ISSUE THREAD

**Issue by binbashroot** [oracle/oci-ansible-collection#18]
Running ansible per doc example results in an empty field in the "Matching Rules" section in UI of the dynamic group
```
 - name: Update AnsibleDynamicGroup Instance Principal Dynamic Group
    oci_identity_dynamic_group:
           compartment_id: ocid1.tenancy.xxxxxxx
           name: AnsibleDynamicGroup
           matching_rule:  instance.compartment.id='ocid1.compartment.oc1.xxxxx'
```
Running Ansible using the following:
```
     - name: Update AnsibleDynamicGroup Instance Principal Dynamic Group
       oci_identity_dynamic_group:
           compartment_id: ocid1.tenancy.oc1..xxxxxx
           name: AnsibleDynamicGroup
           matching_rule: "any {ANY {instance.compartment.id='ocid1.compartment.oc1..xxxxxxxxx', instance.compartment.id='ocid1.compartment.oc1..yyyyyyyyy'}}"
```
will allow the rules to be properly displayed in the UI.
