### ISSUE TITLE
OCI inventory does not includes Mysql DBsystem hosts ip

### ISSUE THREAD

**Issue by nitesh8860** [oracle/oci-ansible-collection#200]
## Issue Report

**Describe the issue**

while fetching inventory from OCI, plugin is not returning oci managed mysql db system hosts

**Expected behavior**

Plugin should include oci managed mysql private ips too

**Environment**

* OS version: Ubuntu 20.04.4 LTS (Focal Fossa)

* Ansible version:

```
ansible [core 2.13.2]
  config file = None
  configured module search path = ['/home/nitesh/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nitesh/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/nitesh/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/nitesh/.local/bin/ansible
  python version = 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

* OCI Python SDK version:

2.90.3

* OCI Ansible Modules version:

oracle.oci 4.10.0   

**Ansible playbook to reproduce the issue**

```
---
plugin: oracle.oci.oci

config_file: ~/.XXXXXXXXX
config_profile: DEFAULT

fetch_db_hosts: true
fetch_compute_hosts: false

regions:
  - XXXXXXXXXX

compartments:
  - compartment_ocid: XXXXXXXXXXX

hostname_format_preferences:
  - "private_ip"

default_groups_preferences:
  compartment_name:
```
Command     
```
ansible-inventory -i inventory.oci.yml --graph
```
Output     
```
@all:      
  |--@ungrouped:
```
