### ISSUE TITLE
Sometimes primary_public_ip and primary_private_ip is null on oci_compute_instance instance status=present response

### ISSUE THREAD

**Issue by williamoliveira** [oracle/oci-ansible-collection#211]
Sometimes primary_public_ip and primary_private_ip is null on oci_compute_instance instance status=present response

![image](https://user-images.githubusercontent.com/6340344/225734901-8c6f6275-4285-4bbd-b856-bfed2798aa80.png)

```yml
- name: Apply server
  oracle.oci.oci_compute_instance:
    config_file_location: "{{ oci_config_path }}"
    config_profile_name: "{{ oci_config_profile }}"
    api_user: "{{ oci_config_api_user }}"
    api_user_fingerprint: "{{ oci_config_api_user_fingerprint }}"
    api_user_key_file: "{{ oci_config_api_user_key_file }}"
    tenancy: "{{ oci_tenancy_id }}"
    region: "{{ oci_region }}"
    availability_domain: "{{ oci_availability_domain}}"
    compartment_id: "{{ oci_compartment_id }}"
    subnet_id: "{{ oci_subnet_id }}"
    display_name: "{{ sub_domain }}"
    source_details:
      source_type: image
      image_id: "{{ oci_image_id }}"
      boot_volume_size_in_gbs: "{{ shape_volume_size_in_gbs }}"
      boot_volume_vpus_per_gb: "{{ shape_volume_vpus_per_gb }}"
    shape_config:
      baseline_ocpu_utilization: "{{ shape_baseline }}"
      memory_in_gbs: "{{ shape_memory }}"
      ocpus: "{{ shape_ocpus }}"
    shape: "VM.Standard.E4.Flex"
    metadata:
      ssh_authorized_keys: "{{ lookup('file',  './files/keys/cloud.pub' ) }}"
    freeform_tags:
      environment: "production"
    state: "{{ server_state }}"
  register: oci_result
  environment:
    OCI_USE_NAME_AS_IDENTIFIER: true
  throttle: 10
  ```

ansible-playbook [core 2.12.5.post0]
  config file = /runner/project/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 2.11.3
  libyaml = True
