### ISSUE TITLE
Listing of PDB's does not work.

### ISSUE THREAD

**Issue by danidorbek** [oracle/oci-ansible-collection#217]
```yaml
    - name: List pluggable_databases
      oci_database_pluggable_database_facts:
        config_profile_name: "{{ conf_profile }}"
        compartment_id: "{{ compartment.lab }}"
        sort_by: PDBNAME
        sort_order: ASC
      register: reg_pdbs
```
returns error:
TASK [List pluggable_databases] ***********************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "error_code": "InvalidParameter", "http_response_status": "400", "module_documentation": "Refer to this link https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/latest/collections/oracle/oci/oci_database_pluggable_database_facts_module.html", "msg": "**Listing resource failed with exception: Invalid pagination token**", "opc_request_id": "request_id_not_shown", "operation_name": "list_pluggable_databases", "request_endpoint": "GET https://database.eu-stockholm-1.oraclecloud.com/20160918/pluggableDatabases", "service_name": "database", "time": "2023-04-11T13:02:16.714239+00:00", "troubleshooting_tips": "Refer to troubleshooting guide https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/latest/guides/troubleshooting-guide.html"}

.
Based on documentation there is no way to set pagination tokens when listing pluggable databases using ansible.

------------ Versions -----------
Collection Version
---------- -------
oracle.oci 4.18.0 

pip freeze | grep oci
oci==2.98.0
