### ISSUE TITLE
Create ansible group when the tag namespace has an illegal character like a dash

### ISSUE THREAD

**Issue by divansantana** [oracle/oci-ansible-collection#231]
So we have a tag namespace such as Oracle-Standard or Oracle-Tags.  How does one work with these namespaces because they have a dash in, something like this does not work:

```
keyed_groups:
  - key: defined_tags.Oracle-Standard.Criticality
    prefix: aaa_crit
    separator: '_'
```

Because `default_groups_preferences` doesn't help, because creating invalid ansible groups like `Oracle-Standard#Criticality=High` is not of much help inside of ansible.

An option to convert illegal characters like # - or = to underscores for the group name, would be nice.

**Comment by divansantana** [comment]
OK, I figured it out, nevermind. :)

```yaml
  - key: defined_tags['Oracle-Standard'].Criticality
    prefix: aaa_crit
    separator: '_'
```
