### ISSUE TITLE
ExaCC/CS   - ansible module : oracle.oci.oci_database_database

### ISSUE THREAD

**Issue by jewdba** [oracle/oci-ansible-collection#242]
## Issue Report

**Describe the issue**

While trying to provision a fresh database on our ExaCC VMcluster the ansible module oracle.oci.oci_database_database used  just returns OK 

**Expected behavior**

Provision a new database according to declared parameters

**Environment**

* OS version: macOS 13.5.1 (22G90)

* Ansible version:

```
# oci-ansible-collection % ansible --version
ansible [core 2.15.3]
  config file = None
  configured module search path = ['/Users/jew/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/8.3.0/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/jew/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.5 (main, Aug 24 2023, 15:18:16) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/usr/local/Cellar/ansible/8.3.0/libexec/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

* OCI Python SDK version:

```
# python -c "import oci;print(oci.__version__)"
2.110.1
```

* OCI Ansible Modules version:

```
# ansible-galaxy collection list oracle.oci

# /<Path>/ansible_collections
Collection Version
---------- -------
oracle.oci 4.28.0
```

**Ansible playbook to reproduce the issue**

```
- name: Deploy Oracle CDB instance
  hosts: localhost
  connection: local
  tasks:
    - name: Deploy CDB
      oracle.oci.oci_database_database:
        compartment_id: ZZZ
        
        database:
          db_name: "CDB1"
          sid_prefix: "CDB1"
          db_unique_name: "CDB1_SITE2"
          admin_password: "Dummy_Passw3rd"
          tde_wallet_password: "Dummy_Passw3rd"
          character_set: "AL32UTF8"
          ncharacter_set: "AL16UTF16"
        source: "NONE"
        db_version: "19.20.0.0.0"
        db_home_id: ZZZ
        state: present
```
