### ISSUE TITLE
oracle.oci.oci_golden_gate_connection missing parameter routing_method

### ISSUE THREAD

**Issue by kjellas** [oracle/oci-ansible-collection#287]
## Issue Report

**Describe the issue**

I'm using this Ansible collection to setup OCI Goldengate Big Data streaming to OCI Streaming Service. As part of this configuration I need to create a connection type KAFKA that will connect to my OCI Stream. Via `oracle.oci.oci_golden_gate_connection` I'm not able to specify `routing_method`. This parameter seems to be missing. The same parameter is available in the OCI Terraform provider.

Specifying `routing_method` in Ansible I get the following error:

`"msg": "Unsupported parameters for (oracle.oci.oci_golden_gate_connection) module: routing_method.`

Ansible doc: https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/5.2.0/collections/oracle/oci/oci_golden_gate_connection_module.html
Terraform doc: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/golden_gate_connection

**Expected behavior**

Should be able to create connection type KAFA where I can specify `routing_method: "SHARED_DEPLOYMENT_ENDPOINT"`.

**Environment**

* OS version: Ubuntu 22.04.4 LTS

* Ansible version:

```
$ansible --version
ansible [core 2.14.5]
  config file = None
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/xxx/.local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

* OCI Python SDK version:

```
$python3 -c "import oci;print(oci.__version__)"
2.126.0
```

* OCI Ansible Modules version:

$ansible-galaxy collection list oracle.oci

```
# /home/xxx/.ansible/collections/ansible_collections
Collection Version
---------- -------
oracle.oci 5.2.0
```

**Ansible playbook to reproduce the issue**

```
- name: Create Connection type OCI Streaming
  oracle.oci.oci_golden_gate_connection:
    compartment_id: "compartment_id_xxxxxxx"
    connection_type: KAFKA
    description: "description_xxxxxxx"
    display_name: "display_name_xxxxxxx"
    password: "SuperStrongSecret"
    routing_method: "SHARED_DEPLOYMENT_ENDPOINT"
    state: present
    stream_pool_id: "ocid1.streampool.oc1.xxxxxxxxxxxx"
    technology_type: OCI_STREAMING
    username: "yyyy/xxxxx-usr/ocid1.streampool.oc1.xxxxxxxxxxxx"
  register: _connection_oss_output
```
