### ISSUE TITLE
oci_object_storage_object does not return object metadata

### ISSUE THREAD

**Issue by CowboyNick** [oracle/oci-ansible-collection#37]
## Issue Report

**Describe the issue**

When retrieving a file from object storage, there doesn't appear to be any way to read the object metadata properties. (i.e. opc-meta-key1, opc-meta-key2)

**Expected behavior**

oci_object_storage_object or oci_object_storage_object_facts should return custom metadata properties.

**Environment**

* OS version: 
 
Oracle Linux 8. 5.4.17-2036.100.6.1.el8uek.x86_64

* Ansible version:
```
ansible 2.10.2
config file = /mnt/hgfs/c/gitlab/nicktest1/nymgitlabrunner/ansible/ansible.cfg
configured module search path = ['/home/nick/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
executable location = /usr/local/bin/ansible
python version = 3.8.3 (default, Nov  4 2020, 23:39:59) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5.0.1)]
```

* OCI Python SDK version:
```
2.26.0
```
* OCI Ansible Modules version:
```
Collection           Version
-------------------- -------
ansible.netcommon    1.4.1
ansible.posix        1.1.1
community.general    1.2.0
community.kubernetes 1.1.1
google.cloud         1.0.1
oracle.oci           2.11.0
```

**Ansible playbook to reproduce the issue**

```
- name: Download object
  oci_object_storage_object:
    namespace_name: namespace_example
    bucket_name: bucket_example
    object_name: object_example
    dest: /usr/local/myobject.txt
```
