### ISSUE TITLE
oci_loadbalancer_certificate

### ISSUE THREAD

**Issue by saracm93** [oracle/oci-ansible-collection#77]
## Issue Report

**Describe the issue**

Unable to add an SSL certificate to OCI Load Balancer issued by LetsEncrypt (acme.sh) via ansible module 
Manually via Console, there is no issue using the same certificates.

**Environment**

* OS version: Ubuntu 20.04.2 LTS

* Ansible version: 2.10.9

* OCI Python SDK version: 2.38.2

**Ansible playbook to reproduce the issue**

- name: LoadBalancer Configuration
  hosts: localhost
  collections:
    - oracle.oci
  connection: local
  vars_files:
    - vars/config.yml
  environment:
    OCI_CONFIG_FILE: "{{ config_file }}"
    OCI_CONFIG_PROFILE: "{{ config_profile }}"
  tasks:
    - name: Add certificate to LoadBalancer
      oci_loadbalancer_certificate:
        load_balancer_id: "---------"
        name: "certificate"
        ca_certificate: "/tmp/cert/ca.cer"
        private_key: "/tmp/cert/private.key"
        public_certificate: "/tmp/cert/fullchain.cer"

-----------------------------------------------------------------------------------
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error accepting ssl configuration. Provided configuration does not have valid private key."}

**Comment by manojmeda** [comment]
@saracm93 The module expects the actual data for the fields `ca_certificate`, `private_key`, `public_certificate` and not the file name. Please refer to the module documentation https://oci-ansible-collection.readthedocs.io/en/latest/collections/oracle/oci/oci_loadbalancer_certificate_module.html#parameters.

You can pass the data from a file using lookup filter like below:

```
- name: Add certificate to LoadBalancer
    oci_loadbalancer_certificate:
    load_balancer_id: "---------"
    name: "certificate"
    ca_certificate: "{{ lookup('file', '/tmp/cert/ca.cer') }}"
    private_key: "{{ lookup('file', '/tmp/cert/private.key') }}"
    public_certificate: "{{ lookup('file', '/tmp/cert/fullchain.cer') }}"
```
