### ISSUE TITLE
Capability to NOT group by all defined tags

### ISSUE THREAD

**Issue by Sneedes** [oracle/oci-ansible-collection#98]
Using the oracle.oci.oci inventory plugin.
Perhaps it's my usage/implementation, but the _default Group by defined tags_ in the code is undesired.  

For example...if I comment out lines 959-971 in oci/plugins/inventory/oci.py, I get _my_ desired functionality.  I have OCI compute instances that have many namespace tags that I don't necessarily want to see nor group on within my Ansible inventory.  

Is there any way functionality can be added so that my inventory will NOT group on EVERY defined tags?
Such as a default/boolean switch to skip this **Group by defined tags** code block?  

```
            # Group by defined tags
            if hasattr(instance, "defined_tags") and instance.defined_tags:
                for namespace in instance.defined_tags:
                    for key in instance.defined_tags[namespace]:
                        defined_tag_group_name = self.sanitize(
                            namespace
                            + "#"
                            + key
                            + "="
                            + instance.defined_tags[namespace][key]
                        )
                        common_groups.add(defined_tag_group_name)
```

For example...the default Oracle tags such as **CreatedOn** have no value for me in an Ansible inventory.

`  |--@Oracle_Tags#CreatedOn=2021-07-20T23_19_25.865Z:
`

Additionally, my team has some inventory/processes/workflow items that dislike seeing the "#" character in the group name.  Don't know the _exact_ details, but stating the "#" character in the group name is breaking some stuff.  Removing the _automatic_ groups of each and every key pair from every tag namespace should remediate this for us.

Please advise what additional information I can provide to assist.

**Comment by Sneedes** [comment]
all.oci.yml

```
plugin: oracle.oci.oci

# Oracle Cloud Infrastructure US Government Cloud with FedRAMP Authorization Regions
regions:
  - us-langley-1
  - us-luke-1

# Set the display name to FQDN, based upon short name + domainName tag
hostname_format_preferences:
  - display_name|lower+'.'+defined_tags.Operations.domainName|lower
  - display_name|lower+'.'+'this.host.needs.a.domainName.tag'

# Create additional groups
keyed_groups:
  - key: defined_tags.Operations.applicationName
    prefix: applicationName
    separator: '_'
  - key: defined_tags.Operations.env
    prefix: env
    separator: '_'

compose:
  ansible_host: display_name+'.'+defined_tags.Operations.domainName
  ansible_ssh_host: private_ip
  cloud: '"oci" if id'

# Only include compute instances tagged with osManagedBy for Ansible
include_host_filters:
  - defined_tags.Operations.osManagedBy=='ansible'

```
